" texmenu.vim
"   Author: Charles E. Campbell, Jr.
"   Date:   Nov 21, 2012
"   Version: 1b  ASTRO-ONLY
" ---------------------------------------------------------------------
"  Load Once: {{{1
if &cp || exists("g:loaded_texmenu") || &enc != 'utf-8'
 finish
endif
let g:loaded_texmenu= "v1b"
let s:keepcpo      = &cpo
set cpo&vim
"DechoTabOn
scriptencoding utf-8

" ---------------------------------------------------------------------
" Options: {{{1
if !exists("g:DrChipTopLvlMenu")
 let g:DrChipTopLvlMenu= "DrChip."
endif

" ---------------------------------------------------------------------
" Menus: {{{1
if !(has("menu") && has("gui_running") && &go =~# 'm')
" call Decho("finishing early")
 finish
endif

" ---------------------------------------------------------------------
" Uppercase Greek: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Α<tab>Alpha	Α'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Β<tab>Beta	Β'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ψ<tab>Psi	\Psi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Δ<tab>Delta	\Delta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ε<tab>Epsilon	Ε'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Φ<tab>Phi	\Phi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Γ<tab>Gamma	\Gamma'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Η<tab>Eta	Η'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ι<tab>Iota	Ι'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ξ<tab>Xi	\Xi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Κ<tab>Kappa	Κ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Λ<tab>Lambda	\Lambda'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Μ<tab>Mu	Μ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ν<tab>Nu	Ν'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ο<tab>Omikron	Ο'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Π<tab>Pi	\Pi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ρ<tab>Rho	Ρ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Σ<tab>Sigma	\Sigma'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Τ<tab>Tau	Τ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Θ<tab>Theta	\Theta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ω<tab>Omega	\Omega'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Χ<tab>Chi	Χ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Υ<tab>Upsilon	\Upsilon'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Capitals.Ζ<tab>Zeta	Ζ'

" ---------------------------------------------------------------------
" Lowercase Greek: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.α<tab>alpha	\alpha'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.β<tab>beta	\beta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.γ<tab>gamma	\gamma'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.δ<tab>delta	\delta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ϵ<tab>epsilon	\epsilon'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ε<tab>varepsilon	\varepsilon'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ζ<tab>zeta	\zeta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.η<tab>eta	\eta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.θ<tab>theta	\theta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ϑ<tab>vartheta	\vartheta'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ι<tab>iota	\iota'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.κ<tab>kappa	\kappa'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.λ<tab>lambda	\lambda'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.μ<tab>mu	\mu'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ν<tab>nu	\nu'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ξ<tab>xi	\xi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ο<tab>omicron	\omicron'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.π<tab>pi	\pi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ϖ<tab>varpi	\varpi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ρ<tab>rho	\rho'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ϱ<tab>varrho	\varrho'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.σ<tab>sigma	\sigma'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ς<tab>varsigma	\varsigma'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.τ<tab>tau	\tau'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.υ<tab>upsilon	\upsilon'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.φ<tab>phi	\phi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ϕ<tab>varphi	\varphi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.χ<tab>chi	\chi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ψ<tab>psi	\psi'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.LowerCase.ω<tab>omega	\omega'

" ---------------------------------------------------------------------
" Arrows: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↺<tab>circlearrowleft	\circlearrowleft'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↻<tab>circlearrowright	\circlearrowright'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↓<tab>downarrow	\downarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇓<tab>Downarrow	\Downarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↩<tab>hookleftarrow	\hookleftarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↪<tab>hookrightarrow	\hookrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↝<tab>leadsto	\leadsto'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟵<tab>leftarrow	\leftarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟸<tab>Leftarrow	\Leftarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↽<tab>leftharpoondown	\leftharpoondown'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↼<tab>leftharpoonup	\leftharpoonup'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇔<tab>leftrightarrow	\leftrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇔<tab>Leftrightarrow	\Leftrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟵<tab>longleftarrow	\longleftarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟸<tab>Longleftarrow	\Longleftarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟷<tab>longleftrightarrow	\longleftrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟺<tab>Longleftrightarrow	\Longleftrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟼<tab>longmapsto	\longmapsto'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟶<tab>longrightarrow	\longrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟹<tab>Longrightarrow	\Longrightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↦<tab>mapsto	\mapsto'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↗<tab>nearrow	\nearrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↖<tab>nwarrow	\nwarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟶<tab>rightarrow	\rightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⟹<tab>Rightarrow	\Rightarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇁<tab>rightharpoondown	\rightharpoondown'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇀<tab>rightharpoonup	\rightharpoonup'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇌<tab>rightleftharpoons	\rightleftharpoons'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↘<tab>searrow	\searrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↙<tab>swarrow	\swarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.↑<tab>uparrow	\uparrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Arrows.⇑<tab>Uparrow	\Uparrow'

" ---------------------------------------------------------------------
" Binary Operators: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∐<tab>amalg	\amalg'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∗<tab>ast	\ast'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.○<tab>bigcirc	\bigcirc'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∇<tab>bigtriangledown	\bigtriangledown'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∆<tab>bigtriangleup	\bigtriangleup'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.•<tab>bullet	\bullet'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∩<tab>cap	\cap'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⋒<tab>Cap	\Cap'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.·<tab>cdot	\cdot'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∘<tab>circ	\circ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∐<tab>coprod	\coprod'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∪<tab>cup	\cup'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⋓<tab>Cup	\Cup'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.†<tab>dagger	\dagger'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.‡<tab>ddagger	\ddagger'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⋄<tab>diamond	\diamond'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.÷<tab>div	\div'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∓<tab>mp	\mp'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊙<tab>odot	\odot'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊖<tab>ominus	\ominus'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊕<tab>oplus	\oplus'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊘<tab>oslash	\oslash'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⋔<tab>pitchfork	\pitchfork'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.±<tab>pm	\pm'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∖<tab>setminus	\setminus'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊓<tab>sqcap	\sqcap'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊔<tab>sqcup	\sqcup'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.✫<tab>star	\star'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.×<tab>times	\times'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊲<tab>triangleleft	\triangleleft'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.⊳<tab>triangleright	\triangleright'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∨<tab>vee	\vee'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.∧<tab>wedge	\wedge'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.≀<tab>wr	\wr'
"exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.BinaryOps.X<tab>uplus	\uplus'

" ---------------------------------------------------------------------
" Delimiters: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.⌊<tab>lfloor	\lfloor'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.<<tab>langle	\langle'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.⌋<tab>rfloor	\rfloor'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.><tab>rangle	\rangle'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.↑<tab>uparrow	\uparrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.↓<tab>downarrow	\downarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.↕<tab>updownarrow	\updownarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.⌈<tab>lceil	\lceil'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.↑<tab>Uparrow	\Uparrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.⇓<tab>Downarrow	\Downarrow'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Delimiters.⌉<tab>rceil	\rceil'

" ---------------------------------------------------------------------
" Miscellaneous Symbols: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.ℵ<tab>aleph	\aleph'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∠<tab>angle	\angle'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∍<tab>backepsilon	\backepsilon'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≃<tab>backsimeq	\backsimeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊼<tab>barwedge	\barwedge'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∵<tab>because	\because'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≬<tab>between	\because'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∎<tab>blacksquare	\blacksquare'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊥<tab>bot	\bot'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊡<tab>boxdot	\boxdot'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊟<tab>boxminus	\boxminus'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊞<tab>boxplus	\boxplus'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊠<tab>boxtimes	\boxtimes'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≏<tab>bumpeq	\bumpeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≎<tab>Bumpeq	\Bumpeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⋯<tab>cdots	\cdots'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♣<tab>clubsuit	\clubsuit'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⋱<tab>ddots	\ddots'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♢<tab>diamondsuit	\diamondsuit'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.ℓ<tab>ell	\ell'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∅<tab>emptyset	\emptyset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∃<tab>exists	\exists'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♭<tab>flat	\flat'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∀<tab>forall	\forall'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.ℏ<tab>hbar	\hbar'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♡<tab>heartsuit	\heartsuit'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∭<tab>iiint	\iiint'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∬<tab>iint	\iint'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.ɩ<tab>imath	\imath'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.ℑ<tab>Im	\Im'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∞<tab>infty	\infty'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∫<tab>int	\int'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.…<tab>ldots	\ldots'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∇<tab>nabla	\nabla'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♮<tab>natural	\natural'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≠<tab>neg	\neg'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∄<tab>nexists	\nexists'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≱<tab>ngeq	\ngeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≱<tab>ngeqq	\ngeqq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≯<tab>ngtr	\ngtr'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≰<tab>nleq	\nleq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≰<tab>nleqq	\nleqq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.≮<tab>nless	\nless'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∤<tab>nmid	\nmid'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∉<tab>notin	\notin'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∮<tab>oint	\oint'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∂<tab>partial	\partial'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.¶<tab>P	\P'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.′<tab>prime	\prime'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.ℜ<tab>Re	\Re'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♯<tab>sharp	\sharp'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.♠<tab>spadesuit	\spadesuit'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.§<tab>S	\S'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.√<tab>surd	\surd'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∴<tab>therefore	\therefore'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⊤<tab>top	\top'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.∆<tab>triangle	\triangle'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.⋮<tab>vdots	\vdots'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.℘<tab>wp	\wp'
"exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Misc.X<tab>jmath	\jmath'

" ---------------------------------------------------------------------
" Number Set Symbols: {{{2
" These need \usepackage{amsfonts} -or-  \usepackage{amssymb}
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.ℙ<tab>prime\ numbers	\mathbb{P}'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.ℕ<tab>natural\ numbers	\mathbb{N}'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.ℤ<tab>integers	\mathbb{Z}'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.I<tab>irrational\ numbers	\mathbb{I}'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.ℚ<tab>rational\ numbers	\mathbb{Q}'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.ℝ<tab>real\ numbers	\mathbb{R}'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.NmbrSets.ℂ<tab>complex\ numbers	\mathbb{C}'

" ---------------------------------------------------------------------
" Relation Symbols: {{{2
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≈<tab>approx	\approx'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≍<tab>asymp	\asymp'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≅<tab>cong	\cong'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊣<tab>dashv	\dashv'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≐<tab>doteq	\doteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≡<tab>equiv	\equiv'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≥<tab>ge	\ge'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≥<tab>geq	\geq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≧<tab>geqq	\geqq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⋛<tab>gtreqless	\gtreqless'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≷<tab>gtrless	\gtrless'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.∈<tab>in	\in'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≤<tab>le	\le'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≤<tab>leq	\leq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≦<tab>leqq	\leqq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⋚<tab>lesseqgtr	\lesseqgtr'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≶<tab>lessgtr	\lessgtr'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.∣<tab>mid	\mid'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≇<tab>ncong	\ncong'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≠<tab>neq	\neq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.∋<tab>ni	\ni'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊀<tab>nprec	\nprec'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊥<tab>perp	\perp'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⪷<tab>precapprox	\precapprox'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⪷<tab>precapprox	\precapprox'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≼<tab>preccurlyeq	\preccurlyeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⪯<tab>preceq	\preceq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⪹<tab>precnapprox	\precnapprox'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⪵<tab>precneqq	\precneqq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≺<tab>prec	\prec'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.∝<tab>propto	\propto'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.∼<tab>sim	\sim'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊑<tab>sqsubseteq	\sqsubseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊏<tab>sqsubset	\sqsubset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊒<tab>sqsupseteq	\sqsupseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊐<tab>sqsupset	\sqsupset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊆<tab>subseteq	\subseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊂<tab>subset	\subset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⪰<tab>succeq	\succeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.≻<tab>succ	\succ'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊇<tab>supseteq	\supseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊃<tab>supset	\supset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Relations.⊢<tab>vdash	\vdash'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.⋈<tab>bowtie	\bowtie'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.⁔<tab>frown	\frown'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.⟫<tab>gg	\gg'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.⟪<tab>ll	\ll'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.╞<tab>models	\models'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.║<tab>parallel	\parallel'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.⋍<tab>simeq	\simeq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.RelationSymbols.‿<tab>smile	\smile'

" ---------------------------------------------------------------------
" Set Symbols: {{{2
" These need \usepackage{amsfonts} -or-  \usepackage{amssymb}
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.SUB<tab>⊂	\subset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.NSUB<tab>⊄	\not\supset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.ESUB<tab>⊆	\supseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.NESUB<tab>⊈	\not\supseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.SUP<tab>⊃	\subset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.NSUP<tab>⊅	\not\subset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.ESUP<tab>⊇	\subseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.NESUP<tab>⊉	\not\subseteq'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.LAND<tab>⋀	\bigwedge'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.LOR<tab>⋁	\bigvee'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.LNOT<tab>¬	\neg'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.EX<tab>∃	\exists'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.NEX<tab>∄	\not\exists'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.EMP<tab>∅	\emptyset'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.EL<tab>∈	\in'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.NEL<tab>∉	\not\in'
exe 'sil! imenu '.g:DrChipTopLvlMenu.'TexSymbols.Sets.ALL<tab>∀	\forall'

"  Restore: {{{1
let &cpo= s:keepcpo
unlet s:keepcpo
" vim: ts=90 fdm=marker
